import "./globals.css";
import { Varela_Round } from "next/font/google";
import Navbar from "./components/Navbar";

const varela = Varela_Round({ subsets: ["latin"], weight: ["400"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={varela.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
